#!/bin/bash

file_name='/home/jose/Documents/GithubProjects/phd-thesis/Documents/Write-Ups/personal_notes/idxdb.tex'

if [[ $1 == "-p" ]]
then
  curr_index=3
  file_name=$2
  if [ ! -f $file_name ] 
  then
    touch $file_name
  fi
else
  curr_index=1
fi

eval "index=\${$curr_index}"
eval "name=\${$[$curr_index+1]}"
eval "description=\${$[$curr_index+2]}"
echo "\newglossaryentry{$index}{name={$name},description={$description}}" >> $file_name
